---
plugins:
  plugin_path: "/home/llama/.config/doing/plugins"
  command_path: "/home/llama/.config/doing/commands"
autotag:
  whitelist: []
  synonyms: {}
editors:
  default: nvim
  doing_file:
  config:
  pager:
disabled_commands: []
doing_file: "~/.local/share/doing/what_was_i_doing.md"
doing_file_sort: desc
backup_dir: "~/.local/share/doing/doing_backup"
history_size: 15
current_section: Currently
paginate: false
never_time: []
never_finish: []
date_tags:
  - done
  - defer(?:red)?
  - waiting
timer_format: text
interval_format: text
templates:
  default:
    date_format: "%Y-%m-%d %H:%M"
    template:
      "%reset%cyan%shortdate %boldwhite%80║ title %boldmagenta[%boldwhite%-10section%boldmagenta]%reset
      %yellow%interval%boldred%duration%white%80_14┃ note"
    wrap_width: 0
    order: asc
  today:
    date_format: "%_I:%M%P"
    template: "%date: %title %interval%duration%note"
    wrap_width: 0
    order: asc
  last:
    date_format: "%-I:%M%P on %a"
    template: "%title (at %date) %interval%duration%odnote"
    wrap_width: 88
  recent:
    date_format: "%_I:%M%P"
    template: "%reset%cyan%shortdate %boldwhite%80┃ title %yellow%interval%boldred%duration%white%80_14┃ note"
    wrap_width: 50
    count: 10
    order: asc
export_templates:
  dayone:
  dayone-days:
  dayone-entries:
  html:
  markdown:
views:
  done:
    date_format: "%_I:%M%P"
    template: "%date | %title (%section)% 18: note"
    wrap_width: 0
    section: All
    count: 0
    order: desc
    tags: done complete cancelled
    tags_bool: OR
  color:
    date_format: "%F %_I:%M%P"
    template: "%boldblack%date %boldgreen| %boldwhite%title%default%note"
    wrap_width: 0
    section: Currently
    count: 10
    order: asc
marker_tag: flagged
marker_color: red
default_tags: []
tag_sort: name
search:
  matching: pattern
  distance: 3
  case: smart
  highlight: false
include_notes: true
interaction:
  confirm_longer_than: 5h
