#!/bin/sh
GRAY="<span rise='2000' font='10' foreground='#ffffff' background='#808080'>"
BLUE="<span foreground='#ffffff' background='#275D84'>"
SPACER="<span font='6'> </span>"
COLOREND="</span>"

UPOWER="$(upower -i /org/freedesktop/UPower/devices/battery_BAT1)"

state="$(echo "$UPOWER" | grep state | awk '{print $2}')"

if [ "$state" = "charging" ]; then
    label=""
    untilfull=$(echo "$UPOWER" | grep "time to full" | awk '{print $4 substr($5,1,1)}')

    watts=$(echo "$UPOWER" | grep energy-rate | awk '{printf("%.1f%s", $2, $3)}')

    echo "${GRAY} ${label} ${COLOREND}${BLUE} $untilfull ${COLOREND}${SPACER}${GRAY}  ${COLOREND}${BLUE} ${watts} ${COLOREND}"

elif [ "$state" = "discharging" ]; then

    percent=$(echo "$UPOWER" | grep percentage | awk '{print $2}' |tr -d "%")

    untilempty=$(echo "$UPOWER" | grep "time to empty" | awk '{print $4 substr($5,1,1)}')

    watts=$(echo "$UPOWER" | grep energy-rate | awk '{printf("%.1f%s", $2, $3)}')

    if [ "$percent" -ge 90 ]; then
        label=""
    elif [ "$percent" -ge 75 ]; then
        label=""
    elif [ "$percent" -ge 50 ]; then
        label=""
    elif [ "$percent" -ge 25 ]; then
        label=""
    elif [ "$percent" -ge 10 ]; then
        label=""
    fi

    echo "${GRAY} ${label} ${COLOREND}${BLUE} $untilempty ${COLOREND}${SPACER}${GRAY}  ${COLOREND}${BLUE} ${watts} ${COLOREND}"
fi

