#!/bin/sh
BAT0="/sys/class/power_supply/BAT0"

status="$(cat ${BAT0}/status)"

capacity=$(cat "${BAT0}/capacity")

energy=$(cat "${BAT0}/energy_now")

power=$(cat "${BAT0}/power_now")

watts=$(echo "scale=2;$power / 1000000" | bc)

GRAY="<span rise='2000' font='10' foreground='#ffffff' background='#808080'>"
BLUE="<span foreground='#ffffff' background='#275D84'>"
SPACER="<span font='6'> </span>"
COLOREND="</span>"


if [ "$status" = "Charging" ] || [ "$status1" = "Charging" ]; then
    label=""

    full=$(cat "${BAT0}/energy_full")

    untilfull=$((full - energy))

    remaining_usage=$(echo "scale=2;${untilfull} / ${power}" | bc)

elif [ "$status" = "Discharging" ] || [ "$status1" = "Discharging" ]; then

    remaining_usage=$(echo "scale=2;${energy} / ${power}" | bc)

    if [ "$capacity" -ge 90 ]; then
        label=""
    elif [ "$capacity" -ge 75 ]; then
        label=""
    elif [ "$capacity" -ge 50 ]; then
        label=""
    elif [ "$capacity" -ge 25 ]; then
        label=""
    elif [ "$capacity" -ge 10 ]; then
        label=""
    fi
else
    exit
fi

hours=$(echo "${remaining_usage}" | awk '{printf "%d", $1}')
minutes=$(echo "${remaining_usage}" | awk '{printf "%0.2d", ($1 % 1) * 60}')

echo "${GRAY} ${label} ${COLOREND}${BLUE} ${hours}:${minutes} ${COLOREND}${SPACER}${GRAY}  ${COLOREND}${BLUE} ${watts} ${COLOREND}"
