#!/bin/bash

drivepath="${BLOCK_INSTANCE:-$HOME}"
rawspace=$(btrfs fi df -b "$drivepath" | sed -e 's/.*total=\([0-9]*\),.*/\1/' | tr "\n" " " | sed -e 's/\ $/\n/' -e 's/\ /\ +\ /g' | bc)
usedspace="$(echo "$rawspace" | awk '{printf "%.2f\n", $1/1024/1024/1024}')"
totalspace="$(df "$drivepath" | tail -n1 | awk '{printf "%.2f\n", $2/1024/1024}')"
freespace=$(printf '%.0f' $(echo "$totalspace" - "$usedspace" | bc -l))

if [ "$freespace" -lt 200 ]; then
  size="${freespace}G"
  echo "<span font='14' foreground='#ffffff' background='#808080'>  </span><span foreground='#ffffff' background='#275D84'> $size </span>"
fi
