#!/bin/env bash

fanspeed=$(cat /sys/devices/platform/asus-nb-wmi/hwmon/hwmon6/fan1_input)

if [ ! $fanspeed -eq 0 ]; then
  echo "<span foreground='#ffffff' background='#808080'>  </span><span foreground='#ffffff' background='#275D84'> ${fanspeed} </span>"
  icon=
fi


