#!/bin/env bash

#memorypercentage="$(free -m | grep Mem| awk '{printf "%.1f%%", $3/$2*100}')"
memoryfree="$(free -h --si | grep Mem | awk '{print $7}')"

if [ "$(free --si | grep Mem | awk '{print $7}')" -lt "2000000" ]; then
	echo "<span foreground='#ffffff' background='#808080'>  </span><span foreground='#ffffff' background='#275D84'> $memoryfree </span>"
fi
