#!/bin/zsh

# This needs to be set in order for autocomplete to work on run shortcut
export PATH="$HOME/bin:$PATH"

# Setup Monitor
xrandr --dpi 192 --output eDP-1 --auto
xrdb -merge ~/.Xresources

# blank screen after 10 minutes
xset s 600 600

# Setup Wallpaper
nitrogen --restore &

# Start Programs
clipster -d &
udiskie &
unclutter &
dunst &
dropbox &
blueman-applet &

# Start Screensaver
xautolock -time 7 -locker "i3lock-fancy" -corners --00  -cornerdelay 4 -cornerredelay 4 -detectsleep &

# enable ctrl-alt-backspace
setxkbmap -option terminate:ctrl_alt_bksp
# Setup keyboard
xmodmap ~/.Xmodmap
xcape -e 'Control_R=Escape;Super_R=Tab'

eval $(ssh-agent)

# Start policy kit
/usr/lib/polkit-1/polkitd --no-debug
