#!/bin/bash

cpuusage="$(mpstat 1 1 | tail -n1 | awk '{printf "%.1f%%", 100 - $12}')"
temp="$(sensors | grep Package | awk '{print $4}' | tr -d '°+')"

if [[ "$temp" ]]; then
    echo "<span foreground='#ffffff' background='#808080'>  </span><span foreground='#ffffff' background='#1478db'> $cpuusage </span><span font='6'> </span><span font='11' rise='1000' foreground='#ffffff' background='#808080'>  </span><span foreground='#ffffff' background='#1478db'> $temp </span>"
else
    echo "<span foreground='#ffffff' background='#808080'>  </span><span foreground='#ffffff' background='#1478db'> $cpuusage </span>"
fi
